<!DOCTYPE html>
<html>
<head>
    <title>Database Backup</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: #4CAF50;
            color: white;
            padding: 10px 20px;
            text-align: center;
            border-radius: 5px;
        }
        .content {
            background: #f9f9f9;
            padding: 20px;
            border-radius: 5px;
            margin-top: 20px;
        }
        .info {
            background: #e7f3ff;
            padding: 10px;
            border-left: 3px solid #2196F3;
            margin: 15px 0;
        }
        .warning {
            background: #fff3cd;
            padding: 10px;
            border-left: 3px solid #ffc107;
            margin: 15px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        td:first-child {
            font-weight: bold;
            width: 40%;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>📀 Database Backup Report</h2>
        </div>
        
        <div class="content">
            <p>Hello,</p>
            <p>Please find attached the database backup for <strong>{{ config('app.name') }}</strong>.</p>
            
            <div class="info">
                <strong>ℹ️ Backup Information:</strong>
                <table>
                    <tr>
                        <td>Database Name:</td>
                        <td><strong>{{ $databaseName }}</strong></td>
                    </tr>
                    <tr>
                        <td>Backup Date & Time:</td>
                        <td><strong>{{ $backupDate }}</strong></td>
                    </tr>
                    <tr>
                        <td>File Size:</td>
                        <td><strong>{{ $backupSize }}</strong></td>
                    </tr>
                    <tr>
                        <td>Application:</td>
                        <td>{{ config('app.name') }}</td>
                    </tr>
                    <tr>
                        <td>Environment:</td>
                        <td>{{ app()->environment() }}</td>
                    </tr>
                </table>
            </div>
            
            <div class="warning">
                <strong>⚠️ Important Notes:</strong>
                <ul>
                    <li>This backup contains sensitive database information.</li>
                    <li>Store this file securely and delete it after use.</li>
                    <li>Do not share this backup with unauthorized personnel.</li>
                    <li>For security reasons, consider encrypting the backup file.</li>
                </ul>
            </div>
            
            <p>The backup file is attached to this email. Keep this file in a secure location.</p>
            
            <p style="margin-top: 20px;">
                Best regards,<br>
                <strong>{{ config('app.name') }} System</strong>
            </p>
        </div>
        
        <div class="footer">
            <p>This is an automated backup notification. Please do not reply to this email.</p>
            <p>Generated by Laravel Backup System</p>
        </div>
    </div>
</body>
</html>